// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBU8cTurBMeqcYWoUZaXxdBcUQ_3sJW4Tc',
    appId: '1:49852035964:web:d8a12b17b1d101566f2af9',
    messagingSenderId: '49852035964',
    projectId: 'food-ordering-40f74',
    authDomain: 'food-ordering-40f74.firebaseapp.com',
    storageBucket: 'food-ordering-40f74.appspot.com',
    measurementId: 'G-FMRXL3X0TJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBDB_AUCerTD7WhKPQTyLscqiqt8AHqPBY',
    appId: '1:49852035964:android:18261b80f1de01886f2af9',
    messagingSenderId: '49852035964',
    projectId: 'food-ordering-40f74',
    storageBucket: 'food-ordering-40f74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAKrEEPlVrb66Uw6a1-FXFeeBdZuUKIpYI',
    appId: '1:49852035964:ios:72bca27230365ef26f2af9',
    messagingSenderId: '49852035964',
    projectId: 'food-ordering-40f74',
    storageBucket: 'food-ordering-40f74.appspot.com',
    iosBundleId: 'com.example.foodiapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAKrEEPlVrb66Uw6a1-FXFeeBdZuUKIpYI',
    appId: '1:49852035964:ios:72bca27230365ef26f2af9',
    messagingSenderId: '49852035964',
    projectId: 'food-ordering-40f74',
    storageBucket: 'food-ordering-40f74.appspot.com',
    iosBundleId: 'com.example.foodiapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBU8cTurBMeqcYWoUZaXxdBcUQ_3sJW4Tc',
    appId: '1:49852035964:web:737dde6f7d12a2ca6f2af9',
    messagingSenderId: '49852035964',
    projectId: 'food-ordering-40f74',
    authDomain: 'food-ordering-40f74.firebaseapp.com',
    storageBucket: 'food-ordering-40f74.appspot.com',
    measurementId: 'G-RF7K59YEF2',
  );
}
